### ISSUE TITLE
Running setup.py install for pythonnet did not run successfully.

### ISSUE THREAD

**Issue by moinabyssinia** [DHI/mikeio1d#28]
Trying to install MIKE IO 1D on windows  `pip install mikeio1d` but keep getting this error

`
Running setup.py install for pythonnet ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pythonnet did not run successfully.       
  │ exit code: 1
  ╰─> [6 lines of output]
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
      
      error: option --single-version-externally-managed not recognized
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pythonnet

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
`

**Comment by murray91** [comment]
Hi! It would help to know which version of python and pip you're using. Could be related to #21

**Comment by moinabyssinia** [comment]
I am using Python 3.9.12 and pip 22.0.4

**Comment by JesperGr** [comment]
mikeio1d is dependent on pythonnet, which is only available for Python 3.8 and lower.

**Comment by JesperGr** [comment]
You may try to install one of the pythonnet 3.0.0 alpha version, which should support Python 3.9 and 3.10.  it is available from

https://github.com/pythonnet/pythonnet/releases
