### ISSUE TITLE
AttributeError:"IRes1DDataSet" object has no attribute 'GetChainages'

### ISSUE THREAD

**Issue by 782910254** [DHI/mikeio1d#35]
Hi, when I read the res1d file using following codes, I got such error. It's weird because in other computers It did work successfully. Do you know how to fix it? is it something related to the environment setting？

from mikeio1d.res1d import Res1D, QueryDataReach
Res1D('HD_test.res1d').read()

Thanks

**Comment by 782910254** [comment]
> 

python 3.8.8

**Comment by 782910254** [comment]
> You should try to install the latest development branch of mikeio1d:
> 
> ```
> pip uninstall mikeio1d
> pip install https://github.com/DHI/mikeio1d/archive/main.zip
> ```
> 
> Unfortunately the version on pypi is a bit behind

thanks, I'll try to update the version and see if this error shows again. :)

**Comment by mathiku** [comment]
I had the same issue on python 3.10 and mikeio1d 0.1.
Upgrading to mikeio1d 0.2 works.

**Comment by leifhealy** [comment]
This issue also caught me out. Is it difficult to update the version in pip to avoid this?

**Comment by gedaskir** [comment]
@leifhealy It seemed like a good day to release mikeio1d 0.2 :-).  Let me know if it works.
