### ISSUE TITLE
Extract specific result type from the res1d

### ISSUE THREAD

**Issue by Q-R-B** [DHI/mikeio1d#55]
Hi,

Is it possible to extract from a res1d only the WaterLevel and drop the DischargeToSurface for example?

thanks for the help

**Comment by gedaskir** [comment]
Hi, to do that you can try:

```python
res1d = Res1D(file_path)
res1d.result_network.nodes.WaterLevel.add()
res1d.result_network.reaches.WaterLevel.add()
res1d.read()
```

**Comment by ecomodeller** [comment]
> Hi, to do that you can try:
> 
> ```python
> res1d = Res1D(file_path)
> res1d.result_network.nodes.WaterLevel.add()
> res1d.result_network.reaches.WaterLevel.add()
> res1d.read()
> ```

I must say that I find this syntax with the `.add()` to be slightly cryptic, I am not sure what I am adding it to🤔

```python
> res1d.result_network.nodes.WaterLevel.add()
> res1d.result_network.reaches.WaterLevel.add()

**Comment by Snowthe** [comment]
> ```python
> res1d = Res1D(file_path)
> res1d.result_network.reaches.WaterLevel.add()
> res1d.read()
> ```

Works fine for me.

> ```python
> res1d.result_network.nodes.WaterLevel.add()
> ```
 ...does not work, however. (mikeio1d 0.4.0. Error message says "AttributeError: 'ResultNodes' object has no attribute 'WaterLevel'" (same happens for Discharge)

In any case, the above was a solution for me wanting to query all discharge across the entire file (like read_all(), but limited to a specified quantity)

I also tried to use QueryDataGlobal. That exists as parts of the queries, but does not seem to be implemented in res1d.read(). I tried to go through the code, but failed to understand how QueryDataGlobal could be implemented there (just like QueryDataNode, QueryDataReach and QueryDataCatchment already are.

If you think that should be implemented - should we open a new issue?

**Comment by Snowthe** [comment]
Thanks for the follow-up, Ryan!
The respective quantities are there:
```python
print(res.quantities)
['WaterLevel', 'Discharge', 'LateralInflowSHEOverland', 'LateralInflowSHESatZone', 'LateralInflowSHEOverlandDrain', 'LateralInflowSHESatZoneDrain']
```
The global query, however:
```python
from mikeio1d import Res1D
[DK7_HIP_100m_running.zip](https://github.com/DHI/mikeio1d/files/12723775/DK7_HIP_100m_running.zip)

from mikeio1d.res1d import QueryDataGlobal
fp = r'DK7_HIP_100m_running.res1d'
res = Res1D(fp)
# print(res.quantities)
qu = QueryDataGlobal('Discharge')
res.read(qu)
```
does not work, and yields a "NoDataForQuery: Invalid query Discharge" error. I tried to work my way through the code myself to understand what's going on, but to no avail.

I attached the .res1d file I used - which originates from a coupled MIKE SHE - HYDRO River setup run in MIKE Zero 2023. Thanks for looking into this.

**Comment by Snowthe** [comment]
Ok, thanks for clarifying that with the GlobalData.

I am not aware of any possiblity of controlling (from the user's/GUI side) how data is stored on nodes/reaches in the .res1d file.

But that means that the recommended way of extracting all Discharge data or WaterLevel data from a .res1d file still is
```python
res1d.result_network.reaches.Discharge.add()
Q = res1d.read()
res1d.result_network.reaches.WaterLevel.add()
WL = res1d.read()
```
(if I don't want to use res1d.read_all() which can get quite big).

Any possiblity to read all Discharge data at a specified timestep?

**Comment by Snowthe** [comment]
Re: Filtering on read:
Yes, typically it works to load the entire file (or all timesteps for a specific quantity), and the filter the resulting dataframe. Just wanted to see if it can be optimized (where we run model ensembles where files potentially are on network drives).

**Comment by Q-R-B** [comment]
> Hi, to do that you can try:
> 
> ```python
> res1d = Res1D(file_path)
> res1d.result_network.nodes.WaterLevel.add()
> res1d.result_network.reaches.WaterLevel.add()
> res1d.read()
> ```

Thanks for the help @gedaskir, it worked well for me.
