### ISSUE TITLE
Can we modify xns11 file

### ISSUE THREAD

**Issue by lj512lj512** [DHI/mikeio1d#8]
Can we write or modify the xns11 file?

**Comment by JesperGr** [comment]
The mikeio1d does not directly include functionality for modifying cross sections. However, the underlying .NET classes does support this, also from Python (those underlying .NET classes is what mikeio1d is using as well).

For examples on using the .NET classes, check out [MIKE 1D SDK Examples](https://github.com/DHI/Mike1D-SDK-examples/tree/master/DHI.Mike1D.Examples) and maybe especially [CrossSectionImExportSimple.cs](https://github.com/DHI/Mike1D-SDK-examples/blob/master/DHI.Mike1D.Examples/CrossSectionImExportSimple.cs)
